// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlfLqAif2HrkST75kok0jNNiqKevArz8w',
    appId: '1:149493315113:web:6708bcd117080cff580e38',
    messagingSenderId: '149493315113',
    projectId: 'memo-app-c859f',
    authDomain: 'memo-app-c859f.firebaseapp.com',
    storageBucket: 'memo-app-c859f.appspot.com',
    measurementId: 'G-QPWP4D02VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBllNtfaqfaBw_aFOB_uQB0iL_aofggRio',
    appId: '1:149493315113:android:617db1b2adde0b88580e38',
    messagingSenderId: '149493315113',
    projectId: 'memo-app-c859f',
    storageBucket: 'memo-app-c859f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbirr4mHeIN9KF-YDDKToEVlM_fn7nicg',
    appId: '1:149493315113:ios:d2db854ccc0d9080580e38',
    messagingSenderId: '149493315113',
    projectId: 'memo-app-c859f',
    storageBucket: 'memo-app-c859f.appspot.com',
    iosBundleId: 'com.example.memoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbirr4mHeIN9KF-YDDKToEVlM_fn7nicg',
    appId: '1:149493315113:ios:d2db854ccc0d9080580e38',
    messagingSenderId: '149493315113',
    projectId: 'memo-app-c859f',
    storageBucket: 'memo-app-c859f.appspot.com',
    iosBundleId: 'com.example.memoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlfLqAif2HrkST75kok0jNNiqKevArz8w',
    appId: '1:149493315113:web:44673672baa669e4580e38',
    messagingSenderId: '149493315113',
    projectId: 'memo-app-c859f',
    authDomain: 'memo-app-c859f.firebaseapp.com',
    storageBucket: 'memo-app-c859f.appspot.com',
    measurementId: 'G-744X73CH0H',
  );
}
